/**
 * Copyright (c) 2021 - 2026 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package dev.buijs.stratastax.entity.core.spi.annotations

import kotlin.reflect.KClass

/**
 * Marks a data class as a root entity.
 *
 * A class that is also a [PersistenceJoin]/[PersistenceJoinMany] group type or a
 * [DomainEntityProjection] is never a root.
 */
@Retention(AnnotationRetention.SOURCE) @Target(AnnotationTarget.CLASS) annotation class DomainEntity

/** Marks a data class as the create command of [entity]. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class CreatesDomainEntity(val entity: KClass<*>)

/** Marks a data class as the update command of [entity]. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class UpdatesDomainEntity(val entity: KClass<*>)

/** Marks a data class as a read-only projection of [target], which must be a [DomainEntity]. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class DomainEntityProjection(val target: KClass<*>)

/** Maps this field to [property] of the create command. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainCreateProperty(val property: String = "")

/** Maps this field to [property] of the update command; see [DomainCreateProperty]. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainUpdateProperty(val property: String = "")

/**
 * Marks a constructor property as generated by the application on create instead of user-supplied.
 *
 * The value is produced by a [dev.buijs.stratastax.entity.core.spi.TypeGenerator]. A [key] is
 * required when multiple properties have the same type but need different generators, or to replace
 * a built-in generator for one property. When blank, the key is derived from the type as
 * `"generate${Type}"`. For example:
 * ```
 * @DomainCreateFunction("ownerId")
 * val ownerId: Long
 * ```
 *
 * The generator must declare the same key:
 * ```
 * internal class GenerateOwnerId : TypeGenerator<Long>("ownerId") {
 *     override fun generate(): Long = ...
 * }
 * ```
 *
 * Mutually exclusive with [PersistenceGenerated]. When combined with [DomainUpdateFunction], both
 * must use the same key.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainCreateFunction(val key: String = "")

/**
 * Marks a constructor property as generated by the application on update instead of user-supplied.
 *
 * Works like [DomainCreateFunction], but the value is regenerated on every update.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainUpdateFunction(val key: String = "")
