/**
 * Copyright (c) 2021 - 2026 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package dev.buijs.stratastax.entity.core.spi.annotations

import kotlin.reflect.KClass

/**
 * Marks a data class as a root entity.
 *
 * A class that is also the group type of [PersistenceJoinOne], [PersistenceJoinMany] or
 * [PersistenceJoinManyThrough], or that is a [DomainEntityProjection], is never a root.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class DomainEntity

/** Marks a data class as a read-only projection of [entity], which must be a [DomainEntity]. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class DomainEntityProjection(
    val entity: KClass<*>,
)

/**
 * Adds this constructor property to the generated create command of its [DomainEntity], named
 * `Create{Entity}`: a plain data class, with no annotations. An entity without such properties has
 * no create command.
 *
 * Nullability follows the entity property. A Kotlin default on the entity property is copied to the
 * command, so `val status: ApprovalStatus = ApprovalStatus.Pending` makes `status` optional on
 * create.
 *
 * @property type The command property type when it can't be derived, such as the id type of a
 *   relation target. Like [RestEntity], only the name is used. [Unit] means derived.
 * @property property The command property name when it must differ from the derived one.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainCreate(
    val type: KClass<*> = Unit::class,
    val property: String = "",
)

/**
 * Adds this constructor property to the generated update command of its [DomainEntity], named
 * `Update{Entity}`, as a `PatchField` that defaults to `PatchField.Unset`. An entity without such
 * properties has no update command.
 *
 * Works like [DomainCreate]. A relation with [PersistenceManageChildren] is only supported with
 * [OneToManyUpdateStrategy.REPLACE_ALL], and is updated with a list of the child's create command.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainUpdate(
    val type: KClass<*> = Unit::class,
    val property: String = "",
)

/**
 * Marks a constructor property as generated by the application on creation instead of user-supplied.
 *
 * The value is produced by a [dev.buijs.stratastax.entity.core.spi.TypeGenerator]. A [key] is
 * required when multiple properties have the same type but need different generators, or to replace
 * a built-in generator for one property. When blank, the key is derived from the type as
 * `"generate${Type}"`. For example:
 * ```
 * @DomainCreateGenerated("ownerId")
 * val ownerId: Long
 * ```
 *
 * The generator must declare the same key:
 * ```
 * internal class GenerateOwnerId : TypeGenerator<Long>("ownerId") {
 *     override fun generate(): Long = ...
 * }
 * ```
 *
 * Mutually exclusive with [PersistenceGenerated]. When combined with [DomainUpdateGenerated],
 * both must use the same key.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainCreateGenerated(
    val key: String = "",
)

/**
 * Marks a constructor property as generated by the application on update instead of user-supplied.
 *
 * Works like [DomainCreateGenerated], but the value is regenerated on every update.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class DomainUpdateGenerated(
    val key: String = "",
)
