/**
 * Copyright (c) 2021 - 2026 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package dev.buijs.stratastax.entity.core.spi.annotations

/**
 * Marks a constructor parameter as backed by a database column.
 *
 * [reference] is a dotted source expression such as `"PLAYSET.PUBLIC_ID"`. When used on a
 * [PersistenceEntity], a bare column name such as `"PUBLIC_ID"` is resolved against the entity's
 * default table. References containing `"."` are used as written.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceColumn(val reference: String = "")

/**
 * Declares the default table of a class so its [PersistenceColumn] references can omit the table.
 *
 * When [table] is blank, it is derived from the uppercased simple class name (`Playset` ->
 * `"PLAYSET"`). The same default is used for persistence join group types.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class PersistenceEntity(val table: String = "")

/** Marks a constructor property as the identity field of the entity. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceId

/** Marks a constructor property as the optimistic-locking version field of the entity. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceVersion

/** Marks a constructor property as the soft-delete column of the entity. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceSoftDelete

/**
 * Marks a constructor property as generated by the database on insert instead of user-supplied.
 *
 * Mutually exclusive with [DomainCreateFunction].
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceGenerated

/**
 * Marks a constructor property as a 1:1 relation to a group type.
 *
 * [from] is the foreign key column of this entity, which follows the same formatting principles as
 * described in [PersistenceColumn]. The key column of the target is resolved from the database
 * schema. How the relation is written is decided by [PersistenceManageLinks] or
 * [PersistenceManageChildren].
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceJoin(val from: String)

/**
 * Marks a constructor parameter as a 1:N relation.
 *
 * [path] describes how the related rows are reached:
 * - 2 elements for a direct foreign-key relation
 * - 3 elements for a junction-table relation
 *
 * The elements identify the tables/columns used to traverse the relation.
 *
 * For example, a direct foreign-key relation can be described as follows, where table MATCH has key
 * ID which is joined on MATCH_ID = MATCH_PARTICIPANT.MATCH_ID.
 *
 * ```
 * @PersistenceJoinMany("MATCH.ID", "MATCH_PARTICIPANT.MATCH_ID")
 * val participants: List<MatchParticipant>
 * ```
 *
 * For example, a junction relation can be described as follows, where table MATCH has key ID which
 * is joined to a junction table MATCH_EXPANSION where MATCH.ID = MATCH_EXPANSION.MATCH_ID and
 * EXPANSION table is joined to MATCH_EXPANSION on EXPANSION.ID = MATCH_EXPANSION.EXPANSION_ID.
 *
 * ```
 * @PersistenceJoinMany(
 *     "MATCH.ID",
 *     "MATCH_EXPANSION.MATCH_ID",
 *     "MATCH_EXPANSION.EXPANSION_ID",
 * )
 * val expansions: List<ExpansionRef>,
 * ```
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceJoinMany(vararg val path: String)

/**
 * Manages only the relation link, never the target rows.
 *
 * The link may be a foreign-key value or junction-table rows.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceManageLinks

/**
 * Manages the target rows of a relation as owned children: they are created, updated, and deleted
 * together with this entity.
 *
 * Applies to [PersistenceJoin] and [PersistenceJoinMany]. Mutually exclusive with
 * [PersistenceManageLinks].
 *
 * For a 1:1 relation, the create/update command must contain a property named after the relation
 * and typed as the target's create/update command.
 *
 * For a 1:N relation, the name matches child command properties.
 *
 * For a junction relation, target rows are deleted as well. Use [PersistenceManageLinks] instead
 * when this entity owns only the junction links.
 *
 * Using this annotation for a target shared with other parents may delete rows still referenced by
 * those parents.
 *
 * [updateStrategy] applies only to direct-FK [PersistenceJoinMany] relations. Junction-table
 * relations always replace their link rows completely.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceManageChildren(
    val updateStrategy: OneToManyUpdateStrategy = OneToManyUpdateStrategy.UPSERT
)

/**
 * How the child rows of a managed direct-FK 1:N group are reconciled on update when the collection
 * is supplied (not [dev.buijs.stratastax.entity.core.api.PatchField.Unset]).
 */
enum class OneToManyUpdateStrategy {
    /**
     * Matches children by identity: updates matches, inserts new elements, deletes missing rows.
     */
    UPSERT,

    /**
     * Deletes all existing children and inserts every supplied element as a new row with an
     * application-generated identity.
     *
     * Nested groups need no strategy of their own because their parent rows are always freshly
     * inserted.
     */
    REPLACE_ALL,
}
