/**
 * Copyright (c) 2021 - 2026 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package dev.buijs.stratastax.entity.core.spi.annotations

/**
 * Marks a constructor parameter as backed by a database column.
 *
 * [reference] is a dotted source expression such as `"PLAYSET.PUBLIC_ID"`. When used on a
 * [PersistenceEntity], a bare column name such as `"PUBLIC_ID"` is resolved against the entity's
 * default table. References containing `"."` are used as written.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceColumn(
    val reference: String,
)

/**
 * Declares the default table of a class so its [PersistenceColumn] references can omit the table.
 *
 * When [table] is blank, it is derived from the uppercased simple class name (`Playset` ->
 * `"PLAYSET"`). The same default is used for persistence join group types.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class PersistenceEntity(
    val table: String = "",
)

/** Marks a constructor property as the identity field of the entity. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceId

/** Marks a constructor property as the optimistic-locking version field of the entity. */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceVersion

/**
 * Marks a constructor property as the soft-delete column of the entity.
 *
 * The column is a nullable timestamp that is set to the current time on delete. Implies
 * `@SearchFixedFilter("null")`, so soft-deleted rows are excluded from search results. Do not
 * combine it with [SearchFilter], [SearchFixedFilter] or [SearchSort].
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceSoftDelete

/**
 * Marks a constructor property as generated by the database on insert instead of user-supplied.
 *
 * Mutually exclusive with [DomainCreateGenerated].
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceGenerated

/**
 * Marks a constructor property as a to-one relation (N:1 or 1:1) through a foreign key of this
 * entity.
 *
 * [foreignKey] is the foreign key column of this entity, which follows the same formatting
 * principles as described in [PersistenceColumn]. The key column it references is resolved from the
 * database schema. How the relation is written is decided by [PersistenceManageLinks] or
 * [PersistenceManageChildren].
 *
 * ```
 * @PersistenceJoinOne("GAME_ID")
 * val game: GameRef,
 * ```
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceJoinOne(
    val foreignKey: String,
)

/**
 * Marks a constructor property as a to-many relation (1:N) through a foreign key of the target.
 *
 * [foreignKey] is the column of the target table that references this entity. A bare column name is
 * resolved against the default table of the target type; the key column it references is resolved
 * from the database schema.
 *
 * Supports [PersistenceManageChildren], but not [PersistenceManageLinks]: the link is part of the
 * target row itself.
 *
 * ```
 * @PersistenceJoinMany("MATCH_PARTICIPANT.MATCH_ID")
 * val participants: List<MatchParticipant>,
 * ```
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceJoinMany(
    val foreignKey: String,
)

/**
 * Marks a constructor property as a to-many relation (M:N) through a junction table.
 *
 * [foreignKey] is the junction column that references this entity and [targetForeignKey] the
 * junction column that references the target. Both must be fully qualified; the key columns they
 * reference are resolved from the database schema.
 *
 * ```
 * @PersistenceJoinManyThrough("MATCH_EXPANSION.MATCH_ID", "MATCH_EXPANSION.EXPANSION_ID")
 * val expansions: List<ExpansionRef>,
 * ```
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceJoinManyThrough(
    val foreignKey: String,
    val targetForeignKey: String,
)

/**
 * Manages only the relation link, never the target rows.
 *
 * The link is the foreign-key value of a [PersistenceJoinOne] or the junction-table rows of a
 * [PersistenceJoinManyThrough]. Not supported on [PersistenceJoinMany].
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceManageLinks

/**
 * Manages the target rows of a relation as owned children: they are created, updated, and deleted
 * together with this entity.
 *
 * Applies to [PersistenceJoinOne], [PersistenceJoinMany] and [PersistenceJoinManyThrough]. Mutually
 * exclusive with [PersistenceManageLinks].
 *
 * For a to-one relation, the create/update command must contain a property named after the relation
 * and typed as the target's create/update command.
 *
 * For a to-many relation, the name matches child command properties.
 *
 * For a junction relation, target rows are deleted as well. Use [PersistenceManageLinks] instead
 * when this entity owns only the junction links.
 *
 * Using this annotation for a target shared with other parents may delete rows still referenced by
 * those parents.
 *
 * [updateStrategy] applies only to [PersistenceJoinMany]. [PersistenceJoinManyThrough] relations
 * always replace their link rows completely.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class PersistenceManageChildren(
    val updateStrategy: OneToManyUpdateStrategy = OneToManyUpdateStrategy.UPSERT,
)

/**
 * How the child rows of a managed [PersistenceJoinMany] group are reconciled on update when the
 * collection is supplied (not [dev.buijs.stratastax.entity.core.api.PatchField.Unset]).
 */
enum class OneToManyUpdateStrategy {

    /**
     * Matches children by identity: updates matches, inserts new elements, deletes missing rows.
     */
    UPSERT,

    /**
     * Deletes all existing children and inserts every supplied element as a new row with an
     * application-generated identity.
     *
     * Nested groups need no strategy of their own because their parent rows are always freshly
     * inserted.
     */
    REPLACE_ALL,
}
